version: '3.9'
services:
  web:
    build:
      context: ./
      target: runner
    image: todo-tailwind
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    platform: linux/amd64